### ISSUE TITLE
Please upload files

### ISSUE THREAD

**Issue by Thundros** [MasatoMakino/threejs-texture-switching-loader#1]
Hi, this project sounds awesome, but there's one problem. There are no files. :( Please upload the project files.

Thanks!

**Comment by MasatoMakino** [comment]
@Thundros 
Thanks for your comment! 

I commit v0.1.0 today.

[Demo Page](https://masatomakino.github.io/threejs-texture-switching-loader/demo/)

Google Chrome 74.0.3729.169 macOS 10.14.5
![](https://www.evernote.com/l/AAnfP-KfvUJHCaVtmuXu9E0NOrZo9KF7K1wB/image.png)
![](https://www.evernote.com/l/AAk33C1KCStBbLUJnv-0G2hvME0a8AGgCN8B/image.png)

Safari 12.1.1 macOS 10.14.5
![](https://www.evernote.com/l/AAmN3ZI_nRBCMojMk7LEAhTBaid3PAITTEkB/image.png)
![](https://www.evernote.com/l/AAk0rGpePQBN_aM1I86BKhxNOwJ_34jdAYoB/image.png)

Please try it.
